- name: create ec2 and r53 records
  hosts: localhost 
  vars: 
    zone: devopsnavyahome.online
    instances:
    - db
    - backend
    - frontend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      name: "{{ item }}"
      security_group: all traffic # replace with your security group name
      image_id: ami-090252cbe067a9e58
      tags:
        name: "{{ item }}"  # settings the names to the instances 

    loop: "{{ instances }}"
    register: ec2_instances_info

  - name: print output
    ansible.builtin.debug:
      msg: "output: {{ ec2_instances_info }}"
  
  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item }}.{{ zone }}"
      type: A
      value: "{{ item.instances.private_ip_address}}"
      overwrite: true
      ttl: 1
    loop: "{{ ec2_instances_info.results.instances }}"
  